### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by techpeace** [matt-snider/vue-guitar-chords#4]
Howdy! I'm interested in using this project in a demo I'm creating of a voice-controlled music education tool.

Would you consider [adding an Open Source license](https://choosealicense.com) so that I can use this project and contribute back?

Thanks!

**Comment by matt-snider** [comment]
Hey! Thanks for pointing out the missing license. 

Your project sounds interesting! I'd be happy to receive contributions if you end up going down that path :-)

**Comment by techpeace** [comment]
Thanks, Matt! I'll definitely let you know once we have something released.
